language: node_js
node_js:
  - "5.11"

script:
  - npm install -g firebase-tools
  - npm install -g firebase

cache:
  directories:
    - node_modules

after_success:
  - firebase deploy --token "${FIREBASE_API_TOKEN}"
